# Generated by Django 4.1 on 2022-09-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('tugilgan_yil', models.DateField()),
                ('soha', models.CharField(max_length=255)),
                ('viloyat', models.CharField(max_length=255)),
                ('rasm', models.FileField(max_length=255, upload_to='')),
            ],
        ),
    ]
